---
title: "Dataviz with ggplot2::theme()"
date: "2022-09-12"
output: html_document
---

# Resources
- colour palette picker + colour-blind simulator: coolors.co
- more on themes: https://ggplot2-book.org/polishing.html
- fonts with `sysfonts`: https://stackoverflow.com/questions/71573377/cannot-import-fonts-into-r
- fonts with `extrafont`: https://uribo.github.io/rpkg_showcase/design/extrafont.html

# Workbook

```{r}
#load libraries
library(tidyverse)
library(bbplot)

#fonts
library(extrafont) 
library(sysfonts)
library(showtext)
```

```{r}
#load data
spp <- read.csv("data/spp_df.csv")[-c(1)]
head(spp)
```

```{r}
#base plot that we are working with to build on
ggplot(data = na.omit(spp), #don't plot NA values
       aes(x = y,
           y = log10(publications), #normalise distribution
           colour = order)) +
  geom_point()
```

```{r}
#some filtering and cleaning up the labels
ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point() +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Order") +
  #adding degree symbol and locking in tick marks so that they don't move around when we make changes
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  #changing values after normalising distribution
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000"))
```

```{r}
#changing colours & customising geom_point
ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point(size = 3,
             alpha = 0.4) +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Order") +
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000")) +
  #colour palette
  scale_colour_manual(values = c("#FAEBB3", "#F7E28D", "#F6DB6E", "#F4D34E", "#F3CC2F",
                               "#f1c40f", "#EFB519", "#EDA722", "#EB982C", "#E98935",
                               "#E97A37", "#E86B39", "#E85B3A", "#e74c3c", "#D14A58",
                               "#BB4875", "#A44691", "#8e44ad", "#7859B9", "#616EC4",
                               "#4B83D0", "#3498db", "#33A5C1", "#31B2A6", "#30BF8C",
                               "#2ECC71", "#4ED487", "#6EDC9D", "#8DE3B2", "#8CE3B2"),
                      #customise the look of legend
                      guide = guide_legend(override.aes = list(size = 6,
                                                               alpha = 1))) 
```

```{r}
#apply some pre-built themes
ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point(size = 3,
             alpha = 0.4) +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Order") +
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000")) +
  scale_colour_manual(values = c("#FAEBB3", "#F7E28D", "#F6DB6E", "#F4D34E", "#F3CC2F",
                               "#f1c40f", "#EFB519", "#EDA722", "#EB982C", "#E98935",
                               "#E97A37", "#E86B39", "#E85B3A", "#e74c3c", "#D14A58",
                               "#BB4875", "#A44691", "#8e44ad", "#7859B9", "#616EC4",
                               "#4B83D0", "#3498db", "#33A5C1", "#31B2A6", "#30BF8C",
                               "#2ECC71", "#4ED487", "#6EDC9D", "#8DE3B2", "#8CE3B2"),
                      guide = guide_legend(override.aes = list(size = 6,
                                                               alpha = 1))) +
  theme_minimal()

ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point(size = 3,
             alpha = 0.4) +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Order") +
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000")) +
  scale_colour_manual(values = c("#FAEBB3", "#F7E28D", "#F6DB6E", "#F4D34E", "#F3CC2F",
                               "#f1c40f", "#EFB519", "#EDA722", "#EB982C", "#E98935",
                               "#E97A37", "#E86B39", "#E85B3A", "#e74c3c", "#D14A58",
                               "#BB4875", "#A44691", "#8e44ad", "#7859B9", "#616EC4",
                               "#4B83D0", "#3498db", "#33A5C1", "#31B2A6", "#30BF8C",
                               "#2ECC71", "#4ED487", "#6EDC9D", "#8DE3B2", "#8CE3B2"),
                      guide = guide_legend(override.aes = list(size = 6,
                                                               alpha = 1))) +
  bbc_style()
```

```{r}
#importing fonts
#if you are using extrafont
font_import() #press y + Enter to add fonts
fonttable()

#if you are using sysfont & showtext
font_add_google("Roboto Condensed")
showtext_auto()
```

```{r}
#creating our own theme
my_theme <- function() {
  theme(axis.title = element_text(family = "Roboto Condensed",
                                  size = 18,
                                  face = "bold"),
        #small tick marks
        axis.text = element_text(family = "Roboto Condensed",
                                 size = 12,
                                 colour = "grey30"),
        axis.line = element_line(size = 0.6,
                                 colour = "grey20"),
        legend.background = element_rect(fill = "white"),
        legend.title = element_text(family = "Roboto Condensed",
                                   size = 18,
                                   face = "bold",
                                   colour = "black"),
        legend.text = element_text(family = "Roboto Condensed",
                                   size = 16,
                                   colour = "black"),
        legend.key = element_rect(fill = "white"),
        legend.position = "right",
        legend.justification = "centre",
        #area outside the panel
        plot.title = element_blank(),
        plot.background = element_rect(fill = "white"),
        #panel is where you datapoints are
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.minor = element_line(colour = "grey90",
                                        linetype = "dashed"))
}

plot <- ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point(size = 3,
             alpha = 0.4) +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Mammalian order") +
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000")) +
  scale_colour_manual(values = c("#FAEBB3", "#F7E28D", "#F6DB6E", "#F4D34E", "#F3CC2F",
                               "#f1c40f", "#EFB519", "#EDA722", "#EB982C", "#E98935",
                               "#E97A37", "#E86B39", "#E85B3A", "#e74c3c", "#D14A58",
                               "#BB4875", "#A44691", "#8e44ad", "#7859B9", "#616EC4",
                               "#4B83D0", "#3498db", "#33A5C1", "#31B2A6", "#30BF8C",
                               "#2ECC71", "#4ED487", "#6EDC9D", "#8DE3B2", "#8CE3B2"),
                      guide = guide_legend(override.aes = list(size = 6,
                                                               alpha = 1),
                                           ncol = 1)) +
  #add you own theme
  my_theme()

ggsave("outputs/plot.pdf", plot, width = 16, height = 9, units = "in", dpi = 300)
```

```{r}
#dark mode!
my_theme_dark <- function() {
  theme(axis.title = element_text(family = "Roboto Condensed",
                                  size = 18,
                                  face = "bold",
                                  colour = "grey95"),
        axis.text = element_text(family = "Roboto Condensed",
                                 size = 12,
                                 colour = "grey70"),
        axis.line = element_line(size = 0.6,
                                 colour = "grey70"),
        legend.background = element_rect(fill = "black"),
        legend.title = element_text(family = "Roboto Condensed",
                                   size = 18,
                                   face = "bold",
                                   colour = "grey95"),
        legend.text = element_text(family = "Roboto Condensed",
                                   size = 16,
                                   colour = "grey90"),
        legend.key = element_rect(fill = "black"),
        legend.position = "right",
        legend.justification = "centre",
        plot.title = element_blank(),
        plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        panel.grid.major = element_line(colour = "grey20"),
        panel.grid.minor = element_line(colour = "grey20",
                                        linetype = "dashed"))
}

plot_dark <- ggplot(data = na.omit(spp),
       aes(x = y,
           y = log10(publications),
           colour = order)) +
  geom_point(size = 3,
             alpha = 0.4) +
  labs(x = "Latitude (median)",
       y = "Number of publications",
       colour = "Mammalian order") +
  scale_x_continuous(breaks = c(-40, 0, 40, 80), 
                     labels = c("-40°", 0, "40°", "80°")) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c(1, 10, 100, "1,000", "10,000")) +
  scale_colour_manual(values = c("#FAEBB3", "#F7E28D", "#F6DB6E", "#F4D34E", "#F3CC2F",
                               "#f1c40f", "#EFB519", "#EDA722", "#EB982C", "#E98935",
                               "#E97A37", "#E86B39", "#E85B3A", "#e74c3c", "#D14A58",
                               "#BB4875", "#A44691", "#8e44ad", "#7859B9", "#616EC4",
                               "#4B83D0", "#3498db", "#33A5C1", "#31B2A6", "#30BF8C",
                               "#2ECC71", "#4ED487", "#6EDC9D", "#8DE3B2", "#8CE3B2"),
                      guide = guide_legend(override.aes = list(size = 6,
                                                               alpha = 1),
                                           ncol = 1)) +
  my_theme_dark()

ggsave("outputs/plot_dark.pdf", plot_dark, width = 16, height = 9, units = "in", dpi = 300)
```
